name: 배포

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      
      # 3. application.properties 생성
      - name: Create application.properties 
        run: |
          touch ./src/main/resources/application.properties
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
          cat ./src/main/resources/application.properties

      # Docker 이미지 빌드 전
      - name: Maven Build
        run: mvn clean package -DskipTests

      # 2. 도커허브 로그인
      - name: 도커허브에 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 이미지 빌드
      - name: 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wookportfolio .

      # 4. 도커허브에 이미지 푸시
      - name: 도커허브에 이미지 푸시
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wookportfolio

      - name: EC2 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          port: 22
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            APP_DIR=/home/ubuntu/wookportfolio

            # Git clone 또는 pull
            if [ ! -d "$APP_DIR/.git" ]; then
              # 기존 소스 초기화 
              sudo rm -rf $APP_DIR
              mkdir -p $APP_DIR

              echo "Git 저장소 없음 → 클론 실행"
              sudo git clone https://github.com/jwba55/wookportfolio.git .
            else
              echo "Git 저장소 있음 → 최신으로 pull"
              cd $APP_DIR
              sudo git reset --hard
              sudo git clean -fd
              sudo git pull origin main
            fi

            # Maven 빌드 (pom.xml 위치 확인)
            cd $APP_DIR   # pom.xml이 있는 디렉터리
            sudo mvn clean package -DskipTests

            # 기존 컨테이너 중지 및 삭제
            if [ $(sudo docker ps -a -q -f name=wookportfolio) ]; then
              sudo docker stop wookportfolio
              sudo docker rm wookportfolio
            fi

            # 최신 이미지 가져오기
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/wookportfolio

            sudo curl http://localhost/.well-known/acme-challenge/test

            # Docker Compose로 springboot-app + nginx 실행
            cd $APP_DIR
            sudo docker-compose up -d --build springboot-app nginx

            sudo docker logs wook-nginx --tail=50